/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package redes.facilitador;

/**
 *
 * @author cesar
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlGeneral = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        pnlInformacion = new javax.swing.JPanel();
        lblArchivo = new javax.swing.JLabel();
        txtArchivo = new javax.swing.JTextField();
        btnArchivo = new javax.swing.JButton();
        lblUbicacion = new javax.swing.JLabel();
        txtUbicacion = new javax.swing.JTextField();
        btnUbicacion = new javax.swing.JButton();
        lblIP = new javax.swing.JLabel();
        comboIP = new javax.swing.JComboBox<>();
        lblEstaciones = new javax.swing.JLabel();
        comboEstaciones = new javax.swing.JComboBox<>();
        pnlHorario = new javax.swing.JPanel();
        lblHora = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        lblMinutos = new javax.swing.JLabel();
        txtMinutos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlGeneral.setBackground(new java.awt.Color(255, 255, 255));
        pnlGeneral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setBackground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("Nombre");
        pnlGeneral.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));
        pnlGeneral.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 180, -1));

        pnlInformacion.setBackground(new java.awt.Color(255, 255, 255));
        pnlInformacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        pnlInformacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblArchivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArchivo.setText("Achivo");
        lblArchivo.setMaximumSize(new java.awt.Dimension(36, 22));
        lblArchivo.setMinimumSize(new java.awt.Dimension(36, 22));
        lblArchivo.setPreferredSize(new java.awt.Dimension(36, 22));
        pnlInformacion.add(lblArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 40, 20));
        pnlInformacion.add(txtArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 130, -1));

        btnArchivo.setText("...");
        btnArchivo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btnArchivo.setBorderPainted(false);
        btnArchivo.setMaximumSize(new java.awt.Dimension(23, 22));
        btnArchivo.setMinimumSize(new java.awt.Dimension(23, 22));
        btnArchivo.setPreferredSize(new java.awt.Dimension(23, 22));
        pnlInformacion.add(btnArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 40, -1));

        lblUbicacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUbicacion.setText("Ubicación");
        lblUbicacion.setMaximumSize(new java.awt.Dimension(53, 22));
        lblUbicacion.setMinimumSize(new java.awt.Dimension(53, 22));
        pnlInformacion.add(lblUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 70, 20));
        pnlInformacion.add(txtUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 130, -1));
        txtUbicacion.getAccessibleContext().setAccessibleParent(pnlInformacion);

        btnUbicacion.setText("...");
        btnUbicacion.setMaximumSize(new java.awt.Dimension(23, 22));
        btnUbicacion.setMinimumSize(new java.awt.Dimension(23, 22));
        btnUbicacion.setPreferredSize(new java.awt.Dimension(23, 22));
        pnlInformacion.add(btnUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 40, -1));
        btnUbicacion.getAccessibleContext().setAccessibleParent(pnlInformacion);

        lblIP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIP.setText("IP");
        lblIP.setMaximumSize(new java.awt.Dimension(36, 22));
        lblIP.setMinimumSize(new java.awt.Dimension(36, 22));
        lblIP.setPreferredSize(new java.awt.Dimension(36, 22));
        pnlInformacion.add(lblIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 40, 20));

        pnlInformacion.add(comboIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 170, -1));

        lblEstaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstaciones.setText("Estaciones");
        lblEstaciones.setMaximumSize(new java.awt.Dimension(53, 22));
        lblEstaciones.setMinimumSize(new java.awt.Dimension(53, 22));
        pnlInformacion.add(lblEstaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 70, 20));

        pnlInformacion.add(comboEstaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 170, -1));

        pnlGeneral.add(pnlInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 530, 110));

        pnlHorario.setBackground(new java.awt.Color(255, 255, 255));
        pnlHorario.setBorder(javax.swing.BorderFactory.createTitledBorder("Horario"));
        pnlHorario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setText("Hora");
        lblHora.setMaximumSize(new java.awt.Dimension(26, 22));
        lblHora.setMinimumSize(new java.awt.Dimension(26, 22));
        lblHora.setPreferredSize(new java.awt.Dimension(26, 22));
        pnlHorario.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 40, -1));
        pnlHorario.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 170, -1));

        lblMinutos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinutos.setText("Minutos");
        lblMinutos.setMaximumSize(new java.awt.Dimension(42, 22));
        lblMinutos.setMinimumSize(new java.awt.Dimension(42, 22));
        lblMinutos.setPreferredSize(new java.awt.Dimension(42, 22));
        pnlHorario.add(lblMinutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 60, -1));
        pnlHorario.add(txtMinutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 170, -1));

        pnlGeneral.add(pnlHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 530, 70));

        pnlPrincipal.add(pnlGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 570, 310));

        getContentPane().add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArchivo;
    private javax.swing.JButton btnUbicacion;
    private javax.swing.JComboBox<String> comboEstaciones;
    private javax.swing.JComboBox<String> comboIP;
    private javax.swing.JLabel lblArchivo;
    private javax.swing.JLabel lblEstaciones;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblIP;
    private javax.swing.JLabel lblMinutos;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblUbicacion;
    private javax.swing.JPanel pnlGeneral;
    private javax.swing.JPanel pnlHorario;
    private javax.swing.JPanel pnlInformacion;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtArchivo;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtMinutos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
